name: 'Setup Action'
description: 'Setup environment for CI'
inputs:
  example-input:
    description: 'An example input'
    required: true
    default: 'default-value'
runs:
  using: 'node12'
  main: 'dist/index.js'