name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested

jobs:
  build-library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Build Action
        run: |
          cd ./.github/actions/setup
          yarn install
          yarn build

      - name: Setup
        uses: ./.github/actions/setup

      - name: Cache yarn dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Clean yarn cache
        run: yarn cache clean

      - name: Install dependencies
        run: yarn install

      - name: Build package
        run: yarn prepare